### ISSUE TITLE
Possible to add video as attachment too ?

### ISSUE THREAD

**Issue by JeofW** [SaeidJavadi/Advanced-WhatsApp-Sender#1]
Would be great if video as attachment is possible

**Comment by SaeidJavadi** [comment]
Will be added in the future

**Comment by Warpupets99** [comment]
Alhamdulillah...

**Comment by TamerElShazly** [comment]
The Script is not working for the images & txt :(

**Comment by SaeidJavadi** [comment]
@TamerElShazly  
Sometimes by changing the whatsapp web, some parts of the code need to be changed.
The code has been updated now and the problem was fixed

**Comment by ketand334** [comment]
If a number is incorrect, the execution gets stuck. Can you please fix that... it would be super helpful.

**Comment by SaeidJavadi** [comment]
@ketand334 
Explain more about this problem

**Comment by ketand334** [comment]
I have noticed couple of bugs here,
1. When sending images with caption after loading multiple numbers, each chat is opened and image is attached and caption is written but the post is not sent. ( click on send button is not working)
2. While loading, if by any chance, an incorrect number is loaded, the code will get stuck and wont iterate to other numbers which are still pending unless there is some manual intervention is done.

**Comment by frencymontana** [comment]
was working perfectly then all of a sudden it loads the image and adds caption but doesn't send

**Comment by SaeidJavadi** [comment]
> 
@ketand334 
Sometimes, these problems occur due to the fact that the version of the Chrome driver and the system's Chrome browser are not the same

**Comment by SaeidJavadi** [comment]
> 
@frencymontana 
We tried to solve this problem
