### ISSUE TITLE
You are not connected to the internet!  Make sure you are connected to the Internet.

### ISSUE THREAD

**Issue by deadlyanony** [SaeidJavadi/Advanced-WhatsApp-Sender#14]
when I click on the start button it gives me the error of the internet is not connected
![error](https://user-images.githubusercontent.com/56093473/191842851-20b8de0e-aa83-4d97-ba73-4994d76864fb.png)

**Comment by SaeidJavadi** [comment]
If you are connected to the Internet, this error will not be displayed, make sure you are connected to the Internet

**Comment by B-Anupam** [comment]
@SaeidJavadi Still, the issue is there. My internet connection is fine.
