### ISSUE TITLE
Error in executing the program

### ISSUE THREAD

**Issue by viditvarshney** [SaeidJavadi/Advanced-WhatsApp-Sender#15]
Hey, I'm facing the below error while executing the program.

When I press the start button, after loading the phone number. It shows below error

![image](https://user-images.githubusercontent.com/34159717/199088211-a254f8fd-9c0d-4dba-8000-04e83e55989e.png)

OS: Windows

**Comment by SaeidJavadi** [comment]
You have not properly installed Python on your system, try to install it properly
