### ISSUE TITLE
errors:

### ISSUE THREAD

**Issue by roybaishali07** [SaeidJavadi/Advanced-WhatsApp-Sender#22]
![image](https://user-images.githubusercontent.com/69315511/224528189-625fe9fb-5920-4ff8-8a4b-2427823f866e.png)
![image](https://user-images.githubusercontent.com/69315511/224528257-4939a6db-e3fc-427f-9227-3cdd853c5daf.png)

**Comment by mdestafadilah** [comment]
any update?

**Comment by SaeidJavadi** [comment]
What is your operating system and Python version?

**Comment by roybaishali07** [comment]
> What is your operating system and Python version?

@SaeidJavadi os:Linux(Fedora)
Python version:3.11.2

**Comment by SaeidJavadi** [comment]
Unfortunately, it does not support Linux well and needs some changes, either you have to complete those changes yourself or give me time to fix them in the future.

**Comment by roybaishali07** [comment]
> Unfortunately, it does not support Linux well and needs some changes, either you have to complete those changes yourself or give me time to fix them in the future.

ya please try to fix it
