### ISSUE TITLE
after Python main.py  don't open the program

### ISSUE THREAD

**Issue by robertnash69** [SaeidJavadi/Advanced-WhatsApp-Sender#23]
First of all, thank you for your contribution. a question, when I run Python. main.py  don't open the program, do you know why?
In advance, thank you for your answer.

Note: I'm using windows 10 pro, Python 3.11.2 and Chrome driver for my browser version

![Sin título](https://user-images.githubusercontent.com/128184038/226004958-33207580-e808-4e06-81e5-c36932a5b57c.png)

**Comment by SaeidJavadi** [comment]
First "Microsoft Visual C++ 14" Install this program completely, and install then all the prerequisites with pip
