### ISSUE TITLE
Excel format

### ISSUE THREAD

**Issue by rizalfsyah7** [SaeidJavadi/Advanced-WhatsApp-Sender#24]
thanks for your project. that's great, but can you give some information about excel format for import number?

**Comment by SaeidJavadi** [comment]
Yes, it is possible

**Comment by budiqx** [comment]
samples for Excel file ?

**Comment by SaeidJavadi** [comment]
> samples for Excel file ?

The program enters any number that exists in the Excel file, and no special format is needed for it
