### ISSUE TITLE
issue in finding the specific path 

### ISSUE THREAD

**Issue by karan30** [SaeidJavadi/Advanced-WhatsApp-Sender#25]
<img width="510" alt="git_issue" src="https://user-images.githubusercontent.com/35443234/233783430-4885187e-c356-4344-b06e-facc92ab3658.PNG">

**Comment by npvchris** [comment]
┌──(npvchristian㉿kalilinux)-[~/Advanced-WhatsApp-Send
└─$ python main.py
Traceback (most recent call last):
  File "/home/npvchristian/Advanced-WhatsApp-Sender/ma
    from PyQt5.QtSql import QSqlDatabase, QSqlQueryMod
ModuleNotFoundError: No module named 'PyQt5.QtSql'

**Comment by SaeidJavadi** [comment]
> ┌──(npvchristian㉿kalilinux)-[~/Advanced-WhatsApp-Send └─$ python main.py Traceback (most recent call last): File "/home/npvchristian/Advanced-WhatsApp-Sender/ma from PyQt5.QtSql import QSqlDatabase, QSqlQueryMod ModuleNotFoundError: No module named 'PyQt5.QtSql'

Hello, probably the prerequisites are not installed properly

**Comment by SaeidJavadi** [comment]
> <img alt="git_issue" width="510" src="https://user-images.githubusercontent.com/35443234/233783430-4885187e-c356-4344-b06e-facc92ab3658.PNG">

Hi, If this path does not exist in the desired folder! Create it manually or clone it again from GitHub
