### ISSUE TITLE
No module named 'selenium.webdriver.common.selenium_manager'

### ISSUE THREAD

**Issue by ProximaCA** [SaeidJavadi/Advanced-WhatsApp-Sender#26]
C:\Users\anon\Desktop\Advanced-WhatsApp-Sender-main>python main.py
Traceback (most recent call last):
  File "C:\Users\anon\Desktop\Advanced-WhatsApp-Sender-main\main.py", line 18, in <module>
    from browserCtrl import Web
  File "C:\Users\anon\Desktop\Advanced-WhatsApp-Sender-main\browserCtrl.py", line 3, in <module>
    from selenium.webdriver.common.selenium_manager import SeleniumManager
ModuleNotFoundError: No module named 'selenium.webdriver.common.selenium_manager'

**Comment by w3labz** [comment]
Use this commend to reinstall selenium driver
`pip install -U selenium`

**Comment by SaeidJavadi** [comment]
Hello, install these two libraries with the following commands
`pip install webdriver-manager`
`pip install chromedriver-autoinstaller`
