### ISSUE TITLE
SyntaxError: unterminated string literal (detected at line 371)

### ISSUE THREAD

**Issue by HamzaOPLEX** [SaeidJavadi/Advanced-WhatsApp-Sender#28]
![image](https://github.com/SaeidJavadi/Advanced-WhatsApp-Sender/assets/53179016/e1dac58a-0031-4726-acb8-0efbbb642455)

**Comment by SaeidJavadi** [comment]
Hello
Unfortunately, it does not work well in Linux
I hope to complete it in the near future
