### ISSUE TITLE
bugs loderstopping thread...

### ISSUE THREAD

**Issue by Bintangelfandri** [SaeidJavadi/Advanced-WhatsApp-Sender#3]
The application always stops when I want to send an order, please fix this function

check user
user True
import
import
{'085722222354'}
Connected to Database
Table OK
C:/Users/Pictures/Camera Roll/nfs.jpg
loder
close app
loder
close app
Startcheck user

True True
image tab
sent textuser True

login
[6285722222354]
find 6285722222354
loderstopping thread...

**Comment by SaeidJavadi** [comment]
Thank you for informing
Sometimes by changing the whatsapp web, some parts of the code need to be changed.
The code has been updated now and the problem was fixed and you can use it 🙏🏻
