### ISSUE TITLE
You are not connected to the Internet!

### ISSUE THREAD

**Issue by Bintangelfandri** [SaeidJavadi/Advanced-WhatsApp-Sender#4]
new isue You are not connected to the Internet!

**Comment by SaeidJavadi** [comment]
When running the program, your system must be connected to the Internet so that it can open the web version of the WhatsApp

**Comment by Bintangelfandri** [comment]
you try ... my computer and system are all connected to the internet 24 hours ... 

check user No internet connection available.
False True user True

Add Account

DevTools listening on ws://127.0.0.1:60679/devtools/browser/d63fc417-8366-4826-b9c1-73c044b1c137
Add Account ->: Message: session not created: This version of ChromeDriver only supports Chrome version 98
Current browser version is 101.0.4951.67 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe     
Stacktrace:
Backtrace:
        Ordinal0 [0x00797AC3+2587331]
        Ordinal0 [0x0072ADD1+2141649]
        Ordinal0 [0x00623BB8+1063864]
        Ordinal0 [0x00643638+1193528]
        Ordinal0 [0x0063F4B5+1176757]
        Ordinal0 [0x0063CC51+1166417]
        Ordinal0 [0x0066D12F+1364271]
        Ordinal0 [0x0066CD5A+1363290]
        Ordinal0 [0x006684A6+1344678]
        Ordinal0 [0x006453F6+1201142]
        Ordinal0 [0x006462E6+1204966]
        GetHandleVerifier [0x0093DF22+1680738]
        GetHandleVerifier [0x009F0DBC+2413564]
        GetHandleVerifier [0x0082D151+563089]
        GetHandleVerifier [0x0082BF13+558419]
        Ordinal0 [0x0073081E+2164766]
        Ordinal0 [0x00735508+2184456]
        Ordinal0 [0x00735650+2184784]
        Ordinal0 [0x0073F5BC+2225596]
        BaseThreadInitThunk [0x76B4FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77E27A7E+286]
        RtlGetAppContainerNamedObjectPath [0x77E27A4E+238]

**Comment by Bintangelfandri** [comment]
I managed to solve this problem. by changing server below
thanks for the very useful GUI code

def ConnectionCheck(self, url='http:

**Comment by SaeidJavadi** [comment]
I solved this problem with the last commit  🙏🏻
