### ISSUE TITLE
python stops working. Not able to add sender account

### ISSUE THREAD

**Issue by ssl-user-en** [SaeidJavadi/Advanced-WhatsApp-Sender#6]
I've been facing this issue running the tool.

\waitingspinnerwidget.py", line 162, in updatePosition
    self.move(self.parentWidget().width() / 2 - self.width() / 2,
TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'float'
  move(self, int, int): argument 1 has unexpected type 'float'

**Comment by SaeidJavadi** [comment]
Recommended to use Python version 3.9.10
