### ISSUE TITLE
error while loading csv

### ISSUE THREAD

**Issue by zgtibu** [SaeidJavadi/Advanced-WhatsApp-Sender#7]
self.move(self.parentWidget().width() / 2 - self.width() / 2,
TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'float'
  move(self, int, int): argument 1 has unexpected type 'float'

**Comment by SaeidJavadi** [comment]
use python 3.9.10 and requirements.txt

**Comment by zgtibu** [comment]
using 3.10

**Comment by SaeidJavadi** [comment]
use python 3.9.10
