### ISSUE TITLE
Number error

### ISSUE THREAD

**Issue by zgtibu** [SaeidJavadi/Advanced-WhatsApp-Sender#8]
I installed python 3.9.10 as per your instructions. now it is working fine.
But the number importing from CSV is having an error while adding country code

if i add 10 digits it will come as the same but if i add include a country code then it is coming as wrong

eg 919898989898 but in program, it is coming as 989198989898. Please guide me.

**Comment by zgtibu** [comment]
i changed area code to 91 but still getting an error not valid url

**Comment by SaeidJavadi** [comment]
Top left of the app, change the number 98 to 91

If there is another error, explain it in more detail so I can help you
